name: Go
on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.21
          check-latest: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - uses: actions/checkout@v4
      - name: test and build
        run: |
          go vet ./...
          # go test ./...
